### ISSUE TITLE
kdirnotify_stub.h: No such file

### ISSUE THREAD

**Issue by PluMGMK** [heliocastro/kde2#2]
When I try to compile, I get to "[ 37%] Generating kdirnotify_stub.moc" and then it fails with:
moc: ~/src/kde2/build/kdelibs/kio/kdirnotify_stub.h: No such file
I get the feeling I'm supposed to have this file as part of some dependency already on my system, but what?

**Comment by PluMGMK** [comment]
Solved manually:
`cd ~/src/kde2/build/kdelibs/kio
../dcop/dcopidl/dcopidl ~/src/kde2/kdelibs/kio/kdirnotify.h >> kdirnotify.kidl
../dcop/dcopidl2cpp/dcopidl2cpp kdirnotify.kidl`

**Comment by heliocastro** [comment]
Hi. Happy new year and I'm on travel to celebrate the passage. This is a cmake bug and thanks to report. I will fix when I back from the Holliday's.

**Comment by heliocastro** [comment]
Fixed.
Stub was not suppose to have moc generation.
Anyway, you found a logic issue on the cmake files, but for now i will not touch that since is not affecting the compilation right now.
Thanks for reporting
