### ISSUE TITLE
Unknown argument HAVE_SYS_MOUNT_H on FreeBSD

### ISSUE THREAD

**Issue by interkosmos** [heliocastro/kde2#8]
Running CMake on FreeBSD 11 leads to:

    CMake Error at /usr/local/share/cmake/Modules/CheckIncludeFiles.cmake:63 (message):
      Unknown arguments:

        HAVE_SYS_MOUNT_H

    Call Stack (most recent call first):
      kdelibs/cmake/kde2_configure.cmake:15 (check_include_files)
      kdelibs/CMakeLists.txt:125 (create_kde2_config_header)

To fix this, change line 15 in file ``kdelibs/cmake/kde2_configure.cmake`` from:

        check_include_files(sys/mount.h HAVE_SYS_MOUNT_H)

to:

        check_include_files(sys/param.h HAVE_SYS_PARAM_H)
        check_include_files(sys/mount.h HAVE_SYS_MOUNT_H)

**Comment by heliocastro** [comment]
Done
